### ISSUE TITLE
Add Contributing md

### ISSUE THREAD

**Issue by fluffyP4nd4** [fluffyP4nd4/NoteIt#3]
Add the contribution guidelines and any other required files

**Comment by nicomartin8542** [comment]
Hi, how are you? I would like to take care of this issue. I am a newbie and trying to do my first PR. What would you be needing to add README.MD?

**Comment by fluffyP4nd4** [comment]
@nicomartin8542  can you find out the steps on how to contribute to a project in GitHub then put them in a Contribution.md files and then send the pr to this repository

**Comment by fluffyP4nd4** [comment]
If you want to take this I'll assign it to you.

**Comment by nicomartin8542** [comment]
Perfect, I fork your project and add some functionality to later make a pool of requests. Thanks a lot

**Comment by fluffyP4nd4** [comment]
Ok add whatever functionality you want.

**Comment by nicomartin8542** [comment]
Hello, I sent the PR for approval. I await your comments. Greetings.

**Comment by fluffyP4nd4** [comment]
Ok I'll just merge it if any issues or bug pop up ill create another issue for fixing that bug.

**Comment by nicomartin8542** [comment]
Perfect, I remain at your disposal. Thanks a lot.
